### ISSUE TITLE
Update to debian stable

### ISSUE THREAD

**Issue by nanu-c** [jshimko/meteor-launchpad#121]
Support for Debian Jessie ends on June 30, 2020, until then, the base docker image has to be updated to stretch :)

**Comment by iehdk** [comment]
Possibly refer to Debian stable and not a named release?

**Comment by nanu-c** [comment]
Would be great

**Comment by imhazige** [comment]
It already not work now because of this issue.
https://lists.debian.org/debian-devel-announce/2019/03/msg00006.html
https://github.com/docker-library/official-images/issues/3551

I can not deploy my app.

Could @jshimko make a update?

**Comment by ciaran-finnegan** [comment]
Hi @imhazige & @jshimko,

#130  I've updated to use Debian:stretch and submitted a pull request 

@imhazige - in the interim you can use the following in your Dockerfile

FROM johnnyutahio/meteor-launchpad:latest

And thank you @jshimko for creating and maintaining this repo.

**Comment by DeciderWill** [comment]
> Hi @imhazige & @jshimko,
> 
> #130 I've updated to use Debian:stretch and submitted a pull request
> 
> @imhazige - in the interim you can use the following in your Dockerfile
> 
> FROM johnnyutahio/meteor-launchpad:latest
> 
> And thank you @jshimko for creating and maintaining this repo.

Hi @slartibastfast - thanks for setting that up, you beat me to do it! However when I pull your image I get ```Step 1/1 : FROM johnnyutahio/meteor-launchpad:latest
pull access denied for johnnyutahio/meteor-launchpad, repository does not exist or may require 'docker login'```, have you published your image publicly?

**Comment by johnnyutahio** [comment]
@DeciderWill  Oops I forgot to push it, it should be there now if you try again!

**Comment by vineethmadathil** [comment]
@johnnyutahio I am getting the following error while using `johnnyutahio/meteor-launchpad:latest`. Could you please check.

```[-] Installing MongoDB 3.4.10...

Warning: apt-key output should not be parsed (stdout is not a terminal)
Executing: /tmp/apt-key-gpghome.wGTZTKtGv5/gpg.1.sh --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 0C49F3730359A14518585931BC711F9BA15703C6
gpg: failed to start the dirmngr '/usr/bin/dirmngr': No such file or directory
gpg: connecting dirmngr at '/tmp/apt-key-gpghome.wGTZTKtGv5/S.dirmngr' failed: No such file or directory
gpg: keyserver receive failed: No dirmngr
The command '/bin/sh -c cd $APP_SOURCE_DIR &&   $BUILD_SCRIPTS_DIR/install-deps.sh &&   $BUILD_SCRIPTS_DIR/install-node.sh &&   $BUILD_SCRIPTS_DIR/install-phantom.sh &&   $BUILD_SCRIPTS_DIR/install-graphicsmagick.sh &&   $BUILD_SCRIPTS_DIR/install-mongo.sh &&   $BUILD_SCRIPTS_DIR/install-meteor.sh &&   $BUILD_SCRIPTS_DIR/build-meteor.sh &&   $BUILD_SCRIPTS_DIR/post-build-cleanup.sh' returned a non-zero code: 2```

**Comment by ciaran-finnegan** [comment]
Hi @vineethmadathil 

Can you confirm if you are are choosing to install MONGO locally via launchpad.conf or other means?

If so I think I missed a reference to debian:jessie in the MongoDB installation script. I have corrected and pushed a new version of the docker image if you would like to try again?

FROM johnnyutahio/meteor-launchpad:latest

(Please let me know if this works and I'll submit a new PR)

Thanks.

**Comment by vineethmadathil** [comment]
@slartibastfast I was using build arguments to install MONGO (`--build-arg INSTALL_MONGO=true `). I tried the latest image and I am still getting the same issue.

**Comment by ciaran-finnegan** [comment]
Hi @vineethmadathil 

Thanks for testing. I've changed the default Mongo DB version to 4.0.8. It's now working for me with _(--build-arg INSTALL_MONGO=true)_ if you'd like to try again.

FROM johnnyutahio/meteor-launchpad:latest

@jshimko  - see #130

**Comment by jshimko** [comment]
I apologize for the wait guys.  I haven't had as much available free time to maintain this project as I'd like, but I'll dig into all of this over the weekend and get some updates pushed out.  Thanks for your patience!

**Comment by vineethmadathil** [comment]
> Hi @vineethmadathil
> 
> Thanks for testing. I've changed the default Mongo DB version to 4.0.8. It's now working for me with _(--build-arg INSTALL_MONGO=true)_ if you'd like to try again.
> 
> FROM johnnyutahio/meteor-launchpad:latest
> 
> @jshimko - see #130

It was actually the issue with Mongo DB version. I also tried changing the Mongo version and now it is working for me. Thanks

**Comment by ciaran-finnegan** [comment]
Thanks for testing
